---

- name: Disable firewalled and selinux
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Disable the firewalld service
      service:
        name: firewalld
        state: stopped
        enabled: no

    - name: Disable SELinux
      selinux:
        state: disabled


